# Generated by Django 3.0.1 on 2020-02-17 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iat_valid_after',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 1, 47, 54, 781320, tzinfo=utc)),
        ),
    ]
