# Generated by Django 3.0.1 on 2020-02-25 17:46

import django.contrib.auth.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_saved_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, users.models.nicknameUniqueValidator]),
            preserve_default=False,
        ),
    ]
