# Generated by Django 3.0.1 on 2020-02-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20200225_1801'),
        ('users', '0012_auto_20200225_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_task_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='schedules.RequestData'),
        ),
    ]
