# Generated by Django 3.0.1 on 2019-12-23 04:36

import courses.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('term', models.PositiveIntegerField(validators=[courses.validators.validate_termcode])),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=20)),
                ('need_clearance', models.BooleanField()),
                ('registered', models.CharField(max_length=20)),
                ('instructor', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=7)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.Course')),
            ],
        ),
    ]
