# Generated by Django 3.0.1 on 2019-12-22 03:23

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.PositiveIntegerField(validators=[courses.validators.validate_termcode]),
        ),
    ]
