# Generated by Django 3.0.1 on 2019-12-23 13:11

import courses.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, size=7, validators=[courses.validators.validate_days_array]),
        ),
    ]
