# Generated by Django 3.0.1 on 2020-01-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_fetched',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
