# Generated by Django 3.0.1 on 2020-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
