# Generated by Django 3.0.1 on 2020-01-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_order_fetched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['course', 'order_fetched']},
        ),
    ]
