# Generated by Django 3.0.1 on 2019-12-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191222_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='need_clearance',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
