# Generated by Django 3.0.1 on 2020-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_remove_schedule_sections'),
        ('courses', '0003_auto_20200103_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='schedules',
            field=models.ManyToManyField(related_name='sections', to='schedules.Schedule'),
        ),
    ]
