# Generated by Django 3.0.1 on 2019-12-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191223_0127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'term')},
        ),
    ]
