# Generated by Django 3.0.1 on 2020-02-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200218_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
