# Generated by Django 3.0.1 on 2020-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200112_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
