# Generated by Django 3.0.1 on 2020-01-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_remove_schedule_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='term',
        ),
    ]
