# Generated by Django 3.0.1 on 2020-01-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20200117_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('PS', 'Processing'), ('DN', 'Done'), ('WN', 'Waring'), ('ER', 'Error'), ('EX', 'Uncaught Exception')], max_length=2),
        ),
    ]
