# Generated by Django 3.0.1 on 2020-01-22 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import schedules.validators


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20200118_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='coursebin',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[schedules.validators.coursebin_validator]),
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='preference',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[schedules.validators.preference_validator]),
        ),
    ]
