# Generated by Django 3.0.1 on 2020-01-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20200122_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
    ]
