# Generated by Django 3.0.1 on 2020-01-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20200124_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-task', 'id']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
