# Generated by Django 3.0.1 on 2020-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20200124_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
