# Generated by Django 3.0.1 on 2020-02-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_auto_20200213_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdata',
            name='public',
        ),
    ]
